version: '3.5'

services:
  db:
    image: postgres
    restart: always
    ports:
     - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kafka-mongo-db
    volumes:
    - ../scripts/db-init.sql:/docker-entrypoint-initdb.d/init.sql